// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlXOa9oUhJqzypb4zhVJoVo6rS9cQhR8w',
    appId: '1:820743718911:android:9707fca8346c5c0ef749ca',
    messagingSenderId: '820743718911',
    projectId: 'ecommecerapp',
    storageBucket: 'ecommecerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUNsR5Vaz4Go6Lj8JMTpoyvoam0VNb4yY',
    appId: '1:820743718911:ios:4ddcdfe8a550c8f1f749ca',
    messagingSenderId: '820743718911',
    projectId: 'ecommecerapp',
    storageBucket: 'ecommecerapp.appspot.com',
    androidClientId: '820743718911-7du25s0pejkuvam9asagt1jscgdushi7.apps.googleusercontent.com',
    iosClientId: '820743718911-gm0klphegtmgi4v9sv6dg8qn867m3api.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceappcodoet',
  );
}
